// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonArchive: typeof import('~icons/carbon/archive')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonChevronDown: typeof import('~icons/carbon/chevron-down')['default']
    CarbonChevronUp: typeof import('~icons/carbon/chevron-up')['default']
    CarbonCopy: typeof import('~icons/carbon/copy')['default']
    CarbonDelete: typeof import('~icons/carbon/delete')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonEdit: typeof import('~icons/carbon/edit')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonMove: typeof import('~icons/carbon/move')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonScooter: typeof import('~icons/carbon/scooter')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    Popover: typeof import('@headlessui/vue')['Popover']
    PopoverButton: typeof import('@headlessui/vue')['PopoverButton']
    PopoverPanel: typeof import('@headlessui/vue')['PopoverPanel']
    RadioGroup: typeof import('@headlessui/vue')['RadioGroup']
    RadioGroupLabel: typeof import('@headlessui/vue')['RadioGroupLabel']
    RadioGroupOption: typeof import('@headlessui/vue')['RadioGroupOption']
    README: typeof import('./components/README.md')['default']
    Switch: typeof import('@headlessui/vue')['Switch']
  }
}

export { }
